import localFont from "next/font/local";
import "./globals.css";
import Navber from "@/component/shared/Navber";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased w-full min-h-screen">
        <Navber />
        <div className="w-full">
          {children}
        </div>
      </body>
    </html>
  );
}
